### PR TITLE
[WIP] [RFC] Add wrapper types and additional request methods

### PR DESCRIPTION
**Pull request by jpsamaroo**
This is my first attempt at wrapping up some key parts of the Zabbix API with their own types and associated request methods. This still needs a lot of work, specifically towards documentation and coverage of more of the API. We'll also definitely want some tests for this functionality, although I have no idea how one would do that for Zabbix (do we spool up a demo Zabbix instance for CI?).

As part of my testing, I also found a need to disable SSL verification in HTTP requests (since I was testing against a personal instance without a proper FQDN), so that's included in here too. I'm happy to split this out into a separate PR if desired.

@rahulkp220 I'd appreciate if you could take a quick look when you get the chance and let me know if this seems like the direction you'd like to go in, or if you think we should set things up differently.

EDIT: TODO list for tracking my progress:

- [ ] Convert all positional filters for `get_xyz` to kwargs
- [ ] Change `showres` to `Base.show`
- [ ] Add types and methods for all API endpoints
- [ ] Add all supported filters for each get method
- [ ] Add tests for as many things as possible
- [ ] Document it all

### CODE REVIEW

**Comment by jpsamaroo** [comment]
One immediate problem I see with this: I only give the option to limit searches by host for things like items and triggers. Instead, I'll probably change the `get_xyz` functions to accept things like host, hostgroup, etc. as kwargs, with each kwarg defaulting to `nothing` as a way to opt-out of filtering.

**Comment by jpsamaroo** [comment]
I've realized after thinking on this a bit that this approach isn't going to scale well. There's too many returned fields for each query for us to create and maintain a field in their respective structs for each type of data. Also, this approach is inefficient when one plans to analyse the received data in bulk, such as via JuliaDB, since we'd be first converting to an intermediate format, and _then_ converting to the destination format, and vice-versa.

Instead, I'm going to change the newly-introduced structs to be representations of a query to be performed, in a lazy sense. Concretely, I intend to set things up similar to how Query.jl sets up its operations, where each operation is just a lazy wrapper around previous operations and/or a data source. This way, we could use the `get_xyz` functions to construct our lazy types, and then feed them into a data analysis pipeline (like an `@query` query), and have them act like data sources or sinks, lazily pulling or pushing data as necessary.

To do this, I'm going to probably add a dependency on either Requires.jl, or TableTraits.jl, so that we can easily participate in the Julia data ecosystem without requiring users to write a bunch of extra code. There will still of course be exported functions to perform the actual query and receive the results in the form of a `Dict`.

**Comment by rahulkp220** [comment]
Got super late here.
Have merged these changes, without making a new release.
Happy to add you to the project repo to take more chances to take ownership and commit at will. LMK 🚀

**Comment by jpsamaroo** [comment]
Thanks for the merge and the offer! I no longer use Zabbix (I used it at my last job a few years back :sweat_smile: ), so I probably won't be doing any more work unless I happen upon a system with Zabbix installed. Anyway, let me know if you want me to explain anything here, I can probably guess what the intention of most of this code was :smile:

**Comment by rahulkp220** [comment]
@jpsamaroo that's sad to know and honestly I got very late here. 
I however would love if you can add a bit of README.md updates to showcase how the code now worked. If not, I am still happy to know anything you would like to share here.

I have been myselves a bit dormant in the Julia ecosystem, however, I have been thinking of starting to commit a bit of time back to it.

**Comment by jpsamaroo** [comment]
I'm not sure if I'll get around to writing up docs right now, since I'd need to work through the code and re-interpret it, and I just don't have much time right now.

That said, if you're employed by a company which relies on Zabbix, we could set up a consulting contract with my business for me to assist with development and testing. That makes it possible for me to allocate time explicitly for this purpose and reallocate my existing commitments. Feel free to reach on on the JuliaLang Slack if you're interested :slightly_smiling_face:

**Pull request merged**
